affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 10
grid_eps: 1
grid_range:
- -1
- 1
k: 2
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 4
symbolic.funs_name.0:
- - sin
  - sin
- - sin
  - x^2
- - x
  - x^2
- - sin
  - x^2
- - x
  - sin
symbolic.funs_name.1:
- - x^3
  - x
  - x
  - log
  - sin
symbolic_enabled: true
width:
- - 2
  - 0
- - 5
  - 0
- - 1
  - 0
